# Generated by Django 3.2.13 on 2023-07-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10)),
                ('age', models.IntegerField()),
                ('openness', models.FloatField()),
                ('neuroticism', models.FloatField()),
                ('conscientiousness', models.FloatField()),
                ('agreeableness', models.FloatField()),
                ('extraversion', models.FloatField()),
                ('predicted_personality', models.CharField(max_length=50)),
            ],
        ),
    ]
